---
name: Build with pdflatex
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: sidbasecode_proposal.tex
          working_directory: .
          compiler: pdflatex
          args:
