---
name: release

on:
  release:
    types:
      - published
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sidbasecode_proposal.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sidbasecode_proposal.aux
          compiler: bibtex
          args:
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: sidbasecode_proposal.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: upload pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sidbasecode_proposal.pdf
          asset_name: sidbasecode_proposal.pdf
          asset_content_type: application/pdf
